### ISSUE TITLE
beta to-do features

### ISSUE THREAD

**Issue by ethanaobrien** [emulatorjs/emulatorjs#151]
All features that are in the old version and are not in the beta will be put into a checklist here. Please comment with the feature, do not open an issue

Once these 7 options are done, I will make the beta the default option

- [x] #133 (update ds core)
- [x] #135 (input keymap)
- [x] #136 (pause/play)
- [x] #137 (shaders)
- [x] #139 (cheats)
- [x] Cleanup UI (no menu, etc...)
- [ ] Catch game failed to start?

(possibly) add cores

- [ ] #119 neo geo cd (possibly [this](https://github.com/libretro/neocd_libretro))
- [ ] #128 Dreamcast (possibly [flycast](https://github.com/libretro/flycast))
- [ ] #128, #158 PS2 (possibly [this](https://github.com/libretro/quake2-for-ps2))
- [x] #125 update n64 core

#128 Gamecube/Wii not yet possible, no usable retroarch gamecube implementation (see #187)
#128 PSP not yet possible, no retroarch psp implimentation

<br>

Everything here down are notes for me
- [x] nes core: [libretro-fceumm](https://github.com/libretro/libretro-fceumm)
- [x] snes core: [snes9x](https://github.com/libretro/snes9x)
- [x] gb core: [gambatte-libretro](https://github.com/libretro/gambatte-libretro)
- [x] gba core: [beetle-gba](https://github.com/libretro/beetle-gba-libretro)
- [x] nds core: [desmume](https://github.com/libretro/desmume2015)
- [x] vba core: [vba-next](https://github.com/libretro/vba-next)
- [x] Nintendo 64 core: [mupen64plus-libretro-nx](https://github.com/ethanaobrien/mupen64plus-libretro-nx)

Once all nintendo cores are working I'll move on to the next section

**Comment by AxelMal71** [comment]
#174

**Comment by ethanaobrien** [comment]
Good news everyone! Thanks to @BinBashBanana I was able to build n64 as a beta core! (see https://github.com/BinBashBanana/webretro/issues/6)

For note: the n64 repository I have for the needed changes is here: https://github.com/ethanaobrien/mupen64plus-libretro-nx

Also, in your emscripten build, you must replace `/upstream/emscripten/src/library_webgl.js` with this file (unzip it first):
[library_webgl.zip](https://github.com/ethanaobrien/emulatorjs/files/9247674/library_webgl.zip)
